# -*- coding: utf-8 -*-
"""Web Scrapping (requests and bs4).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vwRTQyRjOgVkjvieiqtTh_7VtdMA8CU9
"""

import requests

"""Now we will use requests to make a GET HTTP request for the following url = 'https://www.python.org/events/python-events/' by making a GET request.

GET - Used to *request* data from a specified resource.

POST - Used to send data to a server to create/update a resource.
"""

url = 'https://www.python.org/events/python-events/'
req = requests.get(url)

req

req.text

req.text[:200]

"""This shows that we have now grabbed the HTML of this web page. So now we can use Beautiful Soup (bs4) module to parse he HTML and retrieve the event data."""

#pip3 install bs4

from bs4 import BeautifulSoup

"""Let's create a BeautifulSoup object and pass it the HTML text."""

soup = BeautifulSoup(req.text, 'lxml')

events = soup.find('ul', {'class':'list-recent-events'})

events

type(events.findAll())

events.findAll('li')

for event in events.findAll('li'):
    d = dict()
    d['name'] = event.find('h3').find('a').text
    d['time'] = event.find('p').find('time').text
    d['location'] = event.find('span', {'class':'event-location'}).text
    
    print(d)

l_head = []
for e in events.findAll('h3'):
    l_head.append(e.find('a').text)
l_head

l_time = []
for e in events.findAll('p'):
    l_time.append(e.find('time').text)
l_time

l_location = []
for e in events.findAll('li'):
    l_location.append(e.find('span', {'class':'event-location'}).text)
l_location

import pandas as pd

df = pd.DataFrame()

df['event'] = l_head
df['time'] = l_time
df['location'] = l_location

df

import pandas as pd

df = pd.DataFrame()

df['name'] = [e.find('a').text for e in events.findAll('h3')]
df['time'] = [e.find('time').text for e in events.findAll('p')]
df['location'] = [e.find('span', {'class':'event-location'}) for e in events.findAll('li')]

df

"""## Things to keep in mind

1. Requests is used to exeucte HTTP requests. It helps in GET and POST request's responses.

2. Requests object holds the results of the request.

3. We use bs4 to do the parsing of the HTML and also finding of content withing the HTML.

## Assignment

Go to the https://www.python.org/jobs/ url and grab all recent jobs posted on the url.
"""

